export const types = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  ADD_PRODUCT_TO_BASKET: "ADD_PRODUCT_TO_BASKET",
  REMOVE_PRODUCT_FROM_BASKET: "REMOVE_PRODUCT_FROM_BASKET",
  PULL_PRODUCT_AMOUNT_FROM_STOCK: "GET_PRODUCT_AMOUNT_FROM_STOCK",
  PUT_PRODUCT_AMOUNT_TO_STOCK: "GIVE_PRODUCT_AMOUNT_TO_STOCK",
  CANCEL_ORDER: "CANCEL_ORDER",
  CONFIRM_ORDER: "CONFIRM_ORDER",
}
